version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

  frontend:
    build: ./client
    ports:
      - 8081:80
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb_data:
