version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - ip-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      tags:
        - elkingsparx/ip2-client:1.0.1
    container_name: frontend-container
    ports:
      - 8081:80
    depends_on:
      - backend
    networks:
      - ip-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      tags:
        - elkingsparx/ip2-backend:1.0.1
    container_name: backend-container
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    networks:
      - ip-network

networks:
  ip-network:
    driver: bridge

volumes:
  mongodb_data:
