---
- name: Deploy Yolo App using Vagrant
  gather_facts: true
  hosts: all
  become: true

  tasks:
    - name: Check if Docker is installed
      command: docker --version
      ignore_errors: true
      register: docker_check
      tags: docker

    - name: Install Docker Community Edition
      block:
        - name: Include Docker Setup Role
          include_role:
            name: docker-setup
      when: docker_check.rc != 0
      tags: docker
    
    - name: Clone Yolo App Git repository
      git:
        repo: https://github.com/eliud-kinyanjui/yolo.git
        dest: /home/vagrant/yolo/
        version: master
        update: yes
      tags: git
    
    # - name: Run Docker Compose
    #   docker_compose:
    #     project_src: /home/vagrant/yolo/
    #     state: present
    #   tags: docker-compose

    - name: Run Docker Compose
      command: docker compose up -d
      args:
        chdir: /home/vagrant/yolo/
      tags: docker-compose