---
- name: Deploy Yolo App using Vagrant
  gather_facts: true
  hosts: all
  become: true

  roles:
    - git-clone-yolo

  tasks:
    - name: Check if Docker is installed
      command: docker --version
      ignore_errors: true
      register: docker_check
      tags: docker

    - name: Install Docker Community Edition
      block:
        - name: Include Docker Setup Role
          include_role:
            name: docker-setup
      when: docker_check.rc != 0
      tags: docker

    - name: Run Docker Compose
      command: docker compose up -d
      args:
        chdir: /home/vagrant/yolo/
      tags: docker-compose