---
- name: Deploy Yolo App using Vagrant
  gather_facts: false
  hosts: all
  become: true  

- name: Setup Docker Environment
  hosts: all
  become: true
  become_method: sudo
  roles:
  - docker-setup
  tags: docker